# Generated by Django 4.1.7 on 2023-03-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0002_category_alter_articles_options_alter_articles_anons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsline.category'),
        ),
    ]
