# Generated by Django 3.2.18 on 2023-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0005_articles_imgurl_alter_articles_anons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='дизлайки'),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='лайки'),
        ),
    ]
