# Generated by Django 4.1.7 on 2023-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('anons', models.CharField(max_length=250, verbose_name='преназав')),
                ('text_in_box', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateTimeField(verbose_name='дата публикации')),
            ],
        ),
    ]
